"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pygame_calculator.py']
DATA_FILES = ['Button.py',
 'CalcButton.py',
 'Calculator.py',
 'NumberButton.py',
 'Screen.py',
 'globals.py']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
